modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Mr-Pineapple/MrPineapplesFoodMod/issues"

[[mods]]
modId="pinesfoodmod"
version="1.2.0"
updateJSONURL="https://raw.githubusercontent.com/Mr-Pineapple/ModUpdateJSON/master/foodmod/update.json"
displayURL="https://mr-pineapple.co.uk/"
displayName="Mr. Pineapple's Food Mod"
logoFile="foodmod.png"
credits=""
authors="Mr. Pineapple"
description="Mr. Pineapple's Food Mod is quite simple... It adds more food!\n\nFrom chocolate to pizzas, this mod will widen the variety of food in the game and hopefully keep Steve happy!"
itemIcon="pinesfoodmod:pizza_board_oak"
configBackground="minecraft:textures/block/stripped_birch_log.png"

[[dependencies.pinesfoodmod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pinesfoodmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
